[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.88"

[dependencies]
anyhow = "1.0"

[lints.clippy]
pedantic = "warn"
nursery = "warn"

[lints.rust]
unsafe_code = "forbid"
